## This file install required R packages for the tutorials when the repo is first binderized
install.packages("tidyverse")
install.packages("rmarkdown")        
install.packages("ggplot2")
install.packages("lubridate")
install.packages("readxl")
install.packages("viridis")
install.packages("ggridges")
install.packages("hrbrthemes")
## libraries needed for advanced tutorial
install.packages("forecast")
install.packages("xts")
install.packages("TSstudio")
install.packages("here")
install.packages("tidymodels")
install.packages("ClusterR")
install.packages("cluster")
install.packages("broom")
install.packages("data.table")
install.packages("corrplot")

